name: Test Action (PR Comment)

on:
  issue_comment:
    types:
      - created

permissions:
  checks: write
  contents: read

jobs:
  test:
    name: Run action
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'run-lint')
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Clone git repo
        uses: actions/checkout@v3

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EVENT_PAYLOAD = "${{ github.event }}"
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL EVENT: $EVENT_PAYLOAD"
          hub pr checkout $PR_NUM

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build action
        run: yarn build

      - name: Run linters
        uses: ./
        with:
          continue_on_error: false
          eslint: true
          prettier: true
          prettier_extensions: "css,html,js,json,jsx,less,md,scss,ts,tsx,vue,yaml,yml"
          neutral_check_on_warning: true
